version: "3.6"
services:
    php:
         build: .
         restart: always
         ports:
             - "8080:80"
         volumes:
             - ../webApp:/var/www/html
             - ./log:/var/log/apache2
             
    appnext:
        image: webappnext:latest
        restart: always
        ports:
            - "40080:3000"
        volumes:
            - ../webappnext:/app # Monte le projet local dans le conteneur
            - ../webappnext/node_modules:/app/node_modules
        working_dir: /app
        command: npm run dev


    mysql:
        image: mysql:8.0
        restart: always
        ports:
            - "43306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=learnagement
            - MYSQL_USER=learnagement
            - MYSQL_PASSWORD=LMent2Change
            - MYSQL_ROOT_PASSWORD=Root2Change
        volumes:
            - ../db/sql:/docker-entrypoint-initdb.d
            - ../db/data:/data
            - ./conf:/etc/mysql/conf.d
            - learnagement_persistent_db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 48080:80
        environment:
            - PMA_HOST=mysql
            - RELATIONA_DISPLAY=D
        volumes:
            - ./phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
volumes:
    learnagement_persistent_db: